// tools/write-version.cjs
import { readFileSync, writeFileSync, mkdirSync } from 'fs';

const pkg = JSON.parse(readFileSync('./package.json', 'utf8'));

const content = `// Auto-generated by npm run version:stamp
export const APP_VERSION = '${pkg.version}';
export const BUILD_DATE = '${new Date().toISOString()}';
`;

mkdirSync('./src', { recursive: true });
writeFileSync('./src/version.ts', content);
console.log('Wrote src/version.ts:', content);
